#!/usr/bin/env bash
# CS2 launch + window detection + autoexec generation.

STEAM_BIN_LAUNCHER=/root/.local/share/Steam/ubuntu12_32/steam

# Generate $CS2_DIR/game/csgo/cfg/<name>.cfg with the given commands.
# Usage: write_autoexec <cfg-name> "cmd1" "cmd2" ...
write_autoexec() {
  local name="$1"; shift
  local dir="$CS2_DIR/game/csgo/cfg"
  mkdir -p "$dir"
  local f="$dir/${name}.cfg"
  : > "$f"
  echo "// auto-generated by game-streamer entrypoint" >>"$f"
  for line in "$@"; do
    printf '%s\n' "$line" >>"$f"
  done
  log "wrote $f"
}

# IPC -applaunch 730 to the running Steam. The actual ubuntu12_32/steam
# binary detects the running instance via lockfile and forwards args via
# IPC; calling steam.sh would just fork a new bootstrap.
# Returns the cs2 process pid via the LAUNCHED_CS2_PID global.
LAUNCHED_CS2_PID=""
launch_cs2_via_steam() {
  local cs2_args=( "$@" )
  log "IPC -applaunch 730 to running Steam"
  log "  args: ${cs2_args[*]}"
  nohup "$STEAM_BIN_LAUNCHER" -applaunch 730 "${cs2_args[@]}" \
    >/tmp/cs2_launch.log 2>&1 &

  # Auto-skip Vulkan shader pre-cache dialog (it can take 10-30 min).
  autoskip_shader_dialog &
  local skipper_pid=$!

  # Wait for cs2 process to spawn.
  for i in $(seq 1 180); do
    LAUNCHED_CS2_PID=$(pgrep -f '/linuxsteamrt64/cs2' | head -1)
    [ -n "$LAUNCHED_CS2_PID" ] && break
    [ $(( i % 15 )) -eq 0 ] && log "  waiting for Steam to spawn cs2 (${i}s)"
    sleep 1
  done

  kill "$skipper_pid" 2>/dev/null || true

  if [ -z "$LAUNCHED_CS2_PID" ]; then
    log "ERROR: Steam never spawned cs2 after 180s"
    log "  /tmp/cs2_launch.log:"
    tail -n 30 /tmp/cs2_launch.log | sed 's/^/    /' >&2 || true
    return 1
  fi
  log "CS2 spawned: pid=$LAUNCHED_CS2_PID"
}

# Background loop: poll for Steam's "Launching Counter-Strike 2 / Processing
# Vulkan shaders" dialog and click Skip. Quietly exits when killed.
autoskip_shader_dialog() {
  while sleep 2; do
    local id
    id=$(xwininfo -display "$DISPLAY" -root -tree 2>/dev/null \
           | awk '/"Launching Counter-Strike 2"/{print $1; exit}')
    if [ -n "$id" ]; then
      log "auto-skipping shader pre-cache dialog ($id)"
      xdotool windowactivate --sync "$id" 2>/dev/null || true
      xdotool key --clearmodifiers Return 2>/dev/null || true
    fi
  done
}

# Wait for the CS2 main window to appear. xwininfo + grep is more
# reliable than xdotool search in headless Xorg.
# Usage: wait_for_cs2_window <timeout-seconds>
wait_for_cs2_window() {
  local timeout="${1:-240}"
  local i
  for i in $(seq 1 "$timeout"); do
    if xwininfo -display "$DISPLAY" -root -tree 2>/dev/null \
         | grep -q 'Counter-Strike 2'; then
      log "CS2 window detected after ${i}s"
      return 0
    fi
    if [ -n "$LAUNCHED_CS2_PID" ] && ! kill -0 "$LAUNCHED_CS2_PID" 2>/dev/null; then
      log "ERROR: cs2 pid $LAUNCHED_CS2_PID exited before window appeared"
      log "  last 40 lines of cs2 log:"
      tail -n 40 /mnt/game-streamer/steam/logs/console-linux.txt 2>/dev/null \
        | sed 's/^/    /' >&2 || true
      return 1
    fi
    [ $(( i % 15 )) -eq 0 ] && log "  waiting for CS2 window (${i}s)"
    sleep 1
  done
  log "ERROR: CS2 window never appeared after ${timeout}s"
  return 1
}

# Cleanly stop CS2 + the GStreamer capture stream. Leaves Steam, Xorg,
# openbox, and pulseaudio alone.
# Usage: quit_cs2 [hard]
quit_cs2() {
  log "stopping cs2"
  pkill -TERM -f '/linuxsteamrt64/cs2' 2>/dev/null || true
  sleep 2
  pkill -KILL -f '/linuxsteamrt64/cs2' 2>/dev/null || true

  log "stopping gstreamer publish stream"
  pkill -TERM -f 'gst-launch.*publish:' 2>/dev/null || true
  sleep 1
  pkill -KILL -f 'gst-launch.*publish:' 2>/dev/null || true

  if [ "${1:-}" = "hard" ]; then
    log "hard mode — clearing source-engine + X locks"
    rm -f /tmp/source_engine_*.lock /tmp/.X*-lock 2>/dev/null || true
  fi
}
