#!/usr/bin/env bash
# Flow 2 — launch CS2 via running Steam (so it auto-updates) and start the
# match-capture stream.
#
# Prerequisite: Steam must already be logged in (run flow 1 first and watch
# the debug stream until you see the friends list / main window).
#
# Required env:
#   MATCH_ID
#   PLAYCAST_URL  *or*  CONNECT_ADDR + CONNECT_PASSWORD

set -uo pipefail
SCRIPT_TAG=run-live

# shellcheck disable=SC1091
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../lib/common.sh"
# shellcheck disable=SC1091
. "$LIB_DIR/xorg.sh"
# shellcheck disable=SC1091
. "$LIB_DIR/stream.sh"
# shellcheck disable=SC1091
. "$LIB_DIR/audio.sh"
# shellcheck disable=SC1091
. "$LIB_DIR/steam.sh"

load_env
require_env MATCH_ID
if [ -z "${PLAYCAST_URL:-}" ]; then
  require_env CONNECT_ADDR CONNECT_PASSWORD
fi

: "${FPS:=30}"
: "${VIDEO_KBPS:=6000}"
: "${CS2_LAUNCH_TIMEOUT:=300}"
: "${CS2_WINDOW_TIMEOUT:=300}"

: "${DEBUG_STREAM_ID:=debug}"

if [ "${DEBUG_CAPTURE:-0}" = "1" ]; then
  say "0. debug capture stream"
  start_xorg
  # debug stream is video-only — audio not useful for visual debugging
  # and avoids contending for the cs2 sink.
  start_capture "$DEBUG_STREAM_ID" 30 4000 true 0
  log "watch debug: https://hls.5stack.gg/${DEBUG_STREAM_ID}/"
fi

# ---------------------------------------------------------------------------
say "1. preflight"
steam_pipe_up || die "Steam isn't running. Run flow 1 (setup-steam) first."
log "  steam pipe up (pid $(cat "$HOME/.steam/steam.pid"))"
xorg_running || die "Xorg isn't up. Run flow 1 (setup-steam) first."
log "  xorg up on $DISPLAY"

# Real Steam needs the genuine steamclient.so for IPC; restore if gbe_fork
# is in the way from a prior session.
restore_real_steamclient

# ---------------------------------------------------------------------------
say "2. clean up stale CS2 / capture for this match"
pkill -9 -f '/linuxsteamrt64/cs2'   2>/dev/null || true
stop_capture "$MATCH_ID"
sleep 1
rm -f /tmp/source_engine_*.lock
rm -f "$CS2_DIR/game/csgo/steam_appid.txt" \
      "$CS2_DIR/game/bin/linuxsteamrt64/steam_appid.txt" 2>/dev/null || true

# ---------------------------------------------------------------------------
say "3. write CS2 autoexec"
CS2_CFG_DIR="$CS2_DIR/game/csgo/cfg"
mkdir -p "$CS2_CFG_DIR"
# Write to BOTH autoexec.cfg and live_autoexec.cfg.
#   autoexec.cfg is auto-loaded by cs2 at engine init — no launch arg
#                required. This is the path that actually gets honored
#                in CS2 (Source 2); +exec from a launch arg is being
#                silently dropped, observed by no `executed live_autoexec`
#                line in cs2's log after multiple launches.
#   live_autoexec.cfg is kept for compatibility with the original script.
if [ -n "${PLAYCAST_URL:-}" ]; then
  cat > "$CS2_CFG_DIR/autoexec.cfg" <<EOF
// auto-generated by src/flows/run-live.sh — playcast mode
con_enable 1
playcast "$PLAYCAST_URL"
EOF
  log "  playcast: $PLAYCAST_URL"
else
  cat > "$CS2_CFG_DIR/autoexec.cfg" <<EOF
// auto-generated by src/flows/run-live.sh — connect mode
con_enable 1
password "$CONNECT_PASSWORD"
connect $CONNECT_ADDR
EOF
  log "  connect: $CONNECT_ADDR"
fi
cp "$CS2_CFG_DIR/autoexec.cfg" "$CS2_CFG_DIR/live_autoexec.cfg"
log "  wrote $CS2_CFG_DIR/autoexec.cfg + live_autoexec.cfg"

# CS2 dlopen()s libpangoft2-1.0.so without the .0 suffix; pre-link.
for base in libpangoft2-1.0 libpango-1.0; do
  if [ ! -e "$CS2_DIR/game/bin/linuxsteamrt64/${base}.so" ] \
     && [ -e "$CS2_DIR/game/bin/linuxsteamrt64/${base}.so.0" ]; then
    ln -sf "${base}.so.0" "$CS2_DIR/game/bin/linuxsteamrt64/${base}.so" || true
  fi
done

# Match the original working invocation: cd into the cs2 binary dir
# before launching. Original observed: cwd matters for some of cs2's
# rpath-relative resolutions during Steam's launch handoff.
CS2_BIN="$CS2_DIR/game/bin/linuxsteamrt64/cs2"
[ -x "$CS2_BIN" ] || die "CS2 binary missing at $CS2_BIN"
cd "$(dirname "$CS2_BIN")"

# ---------------------------------------------------------------------------
say "4. launch CS2"
# Force cs2's audio to the null sink we capture from. Without this,
# cs2 may pick a cached different sink (or no sink at all in headless)
# and we'd capture silence from cs2.monitor. PULSE_SINK is honored by
# the PulseAudio client lib at startup of the app.
export PULSE_SINK="${PULSE_SINK_NAME:-cs2}"
log "  PULSE_SINK=$PULSE_SINK (cs2 audio routes here)"

do_applaunch() {
  # Three independent paths trigger the connect — whichever cs2 honors
  # first wins:
  #   1) autoexec.cfg in cfg/ — cs2 auto-loads this at engine init
  #   2) +exec live_autoexec  — explicit cfg execution via launch arg
  #   3) +connect / +password — direct launch args, run after engine init
  local cs2_args=(
    -fullscreen -width 1920 -height 1080 -novid -nojoy -console
    +exec live_autoexec)
  if [ -n "${PLAYCAST_URL:-}" ]; then
    cs2_args+=(+playcast "$PLAYCAST_URL")
  else
    cs2_args+=(+password "$CONNECT_PASSWORD" +connect "$CONNECT_ADDR")
  fi

  if [ "${LAUNCH_CS2_DIRECT:-0}" = "1" ]; then
    # Bypass Steam's -applaunch handoff. cs2 reads steamclient.so
    # via $HOME/.steam/sdk64/ and talks to the running Steam
    # directly; -applaunch was dropping our +connect args silently.
    local cs2_bin="$CS2_DIR/game/bin/linuxsteamrt64/cs2"
    log "  exec (DIRECT): $cs2_bin ${cs2_args[*]}"
    cd "$CS2_DIR/game/bin/linuxsteamrt64"
    nohup "$cs2_bin" "${cs2_args[@]}" >>"$LOG_DIR/cs2_launch.log" 2>&1 &
    log "  cs2 direct launch (pid=$!)"
  else
    local cmd=("$STEAM_HOME/ubuntu12_32/steam" -applaunch 730 "${cs2_args[@]}")
    log "  exec: ${cmd[*]}"
    nohup "${cmd[@]}" >>"$LOG_DIR/cs2_launch.log" 2>&1 &
    log "  applaunch sent (launcher pid=$!)"
  fi
}
do_applaunch
RELAUNCH_DONE=0

# Wait for cs2 process. Two side-effects on each iteration:
#  - poke the Steam window with Return: dismisses the focused button on
#    any modal CEF dialog (cloud-out-of-date, "Launching ... shaders", etc).
#  - every 15s, dump the open X windows + cs2/launcher state so the
#    operator can see what Steam is actually showing right now.
CS2_PID=""
for i in $(seq 1 "$CS2_LAUNCH_TIMEOUT"); do
  CS2_PID=$(pgrep -f '/linuxsteamrt64/cs2' | head -1)
  [ -n "$CS2_PID" ] && break

  # Auto-poke: Space dismisses Steam's CEF dialogs (cloud-out-of-date,
  # shader pre-cache) by activating the default-focused button. Bounded
  # to the first 90s of the wait — covers a late-appearing dialog while
  # cs2 is downloading cloud files. cs2 spawn breaks the loop so this
  # never fires once the game is up.
  if [ "$i" -ge 3 ] && [ "$i" -le 90 ] && [ $(( i % 5 )) -eq 0 ]; then
    poke_steam_dialog
  fi

  [ $(( i % 15 )) -eq 0 ] && log "  ${i}s elapsed waiting on cs2..."

  # Fallback: if cs2 still hasn't spawned after 30s, re-issue applaunch
  # once. Steam sometimes ignores the very first applaunch on a fresh
  # login (logs "Steam is already running, command line was forwarded"
  # but never spawns cs2). A second applaunch reliably kicks it.
  if [ "$i" = 30 ] && [ "$RELAUNCH_DONE" = 0 ]; then
    log "  30s without cs2 — re-issuing -applaunch (one-shot fallback)"
    do_applaunch
    RELAUNCH_DONE=1
  fi
  sleep 1
done
[ -n "$CS2_PID" ] || {
  warn "Steam never spawned cs2 in ${CS2_LAUNCH_TIMEOUT}s"
  log "--- $LOG_DIR/cs2_launch.log ---"
  tail -40 "$LOG_DIR/cs2_launch.log"
  log "--- $STEAM_LIBRARY/steam/logs/console-linux.txt ---"
  tail -20 "$STEAM_LIBRARY/steam/logs/console-linux.txt" 2>/dev/null || true
  exit 1
}
log "  cs2 pid=$CS2_PID"
ln -sf "$STEAM_LIBRARY/steam/logs/console-linux.txt" "$LOG_DIR/cs2.log" 2>/dev/null || true

# cs2 is up — hide Steam's main UI + Friends List so any missed
# clicks (e.g. from the shader-skip auto-handler) don't fall through
# to Steam buttons behind the dialog. Modal dialogs Steam pops on top
# (shader pre-cache, etc.) remain visible since they're separate
# X windows; only the persistent Steam UI gets hidden.
minimize_steam_windows

# ---------------------------------------------------------------------------
say "5. wait for CS2 window"
WIN=""
for i in $(seq 1 "$CS2_WINDOW_TIMEOUT"); do
  WIN=$(xwininfo -display "$DISPLAY" -root -tree 2>/dev/null \
    | awk '/"Counter-Strike 2"/{print $1; exit}')
  [ -n "$WIN" ] && { log "  window after ${i}s: $WIN"; break; }
  if ! kill -0 "$CS2_PID" 2>/dev/null; then
    warn "cs2 EXITED early."
    dump_log "$LOG_DIR/cs2.log"
    exit 1
  fi
  [ $(( i % 15 )) -eq 0 ] && log "  still waiting for cs2 window (${i}s, pid=$CS2_PID alive)"
  sleep 1
done
[ -n "$WIN" ] || {
  warn "no CS2 window after ${CS2_WINDOW_TIMEOUT}s. cs2.log tail:"
  tail -60 "$LOG_DIR/cs2.log" 2>/dev/null
  exit 1
}

# ---------------------------------------------------------------------------
say "6. start match capture stream"
# 5th arg = 1 → include PulseAudio leg (cs2.monitor → AAC → mpegts mux)
start_capture "$MATCH_ID" "$FPS" "$VIDEO_KBPS" false 1

say "done"
log "watch:    https://hls.5stack.gg/${MATCH_ID}/"
log "cs2 log:  $LOG_DIR/cs2.log"
log "gst log:  $LOG_DIR/gst-${MATCH_ID}.log"
log "stop:     src/game-streamer.sh stop-live"
