#!/usr/bin/env bash
# Flow 2 — launch CS2 via running Steam (so it auto-updates) and start the
# match-capture stream.
#
# Prerequisite: Steam must already be logged in (run flow 1 first and watch
# the debug stream until you see the friends list / main window).
#
# Required env:
#   MATCH_ID
#   PLAYCAST_URL  *or*  CONNECT_ADDR + CONNECT_PASSWORD

set -uo pipefail
SCRIPT_TAG=run-live

# shellcheck disable=SC1091
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../lib/common.sh"
# shellcheck disable=SC1091
. "$LIB_DIR/xorg.sh"
# shellcheck disable=SC1091
. "$LIB_DIR/stream.sh"
# shellcheck disable=SC1091
. "$LIB_DIR/steam.sh"

load_env
require_env MATCH_ID
if [ -z "${PLAYCAST_URL:-}" ]; then
  require_env CONNECT_ADDR CONNECT_PASSWORD
fi

: "${FPS:=30}"
: "${VIDEO_KBPS:=6000}"
: "${CS2_LAUNCH_TIMEOUT:=300}"
: "${CS2_WINDOW_TIMEOUT:=300}"

: "${DEBUG_STREAM_ID:=debug}"

if [ "${DEBUG_CAPTURE:-0}" = "1" ]; then
  say "0. debug capture stream"
  start_xorg
  start_capture "$DEBUG_STREAM_ID" 30 4000 true
  log "watch debug: https://hls.5stack.gg/${DEBUG_STREAM_ID}/"
fi

# ---------------------------------------------------------------------------
say "1. preflight"
steam_pipe_up || die "Steam isn't running. Run flow 1 (setup-steam) first."
log "  steam pipe up (pid $(cat "$HOME/.steam/steam.pid"))"
xorg_running || die "Xorg isn't up. Run flow 1 (setup-steam) first."
log "  xorg up on $DISPLAY"

# Real Steam needs the genuine steamclient.so for IPC; restore if gbe_fork
# is in the way from a prior session.
restore_real_steamclient

# ---------------------------------------------------------------------------
say "2. clean up stale CS2 / capture for this match"
pkill -9 -f '/linuxsteamrt64/cs2'   2>/dev/null || true
stop_capture "$MATCH_ID"
sleep 1
rm -f /tmp/source_engine_*.lock
rm -f "$CS2_DIR/game/csgo/steam_appid.txt" \
      "$CS2_DIR/game/bin/linuxsteamrt64/steam_appid.txt" 2>/dev/null || true

# ---------------------------------------------------------------------------
say "3. write CS2 autoexec"
CS2_CFG_DIR="$CS2_DIR/game/csgo/cfg"
mkdir -p "$CS2_CFG_DIR"
if [ -n "${PLAYCAST_URL:-}" ]; then
  cat > "$CS2_CFG_DIR/live_autoexec.cfg" <<EOF
// auto-generated by src/flows/run-live.sh — playcast mode
con_enable 1
playcast "$PLAYCAST_URL"
EOF
  log "  playcast: $PLAYCAST_URL"
else
  cat > "$CS2_CFG_DIR/live_autoexec.cfg" <<EOF
// auto-generated by src/flows/run-live.sh — connect mode
con_enable 1
password "$CONNECT_PASSWORD"
connect $CONNECT_ADDR
EOF
  log "  connect: $CONNECT_ADDR"
fi

# CS2 ships an older libfreetype.so.6 that resolves first via $ORIGIN rpath
# and then breaks system libharfbuzz. LD_PRELOAD the system copy so it wins.
SYS_FREETYPE=/lib/x86_64-linux-gnu/libfreetype.so.6
[ -e "$SYS_FREETYPE" ] && export LD_PRELOAD="$SYS_FREETYPE${LD_PRELOAD:+:$LD_PRELOAD}"

# CS2 dlopen()s libpangoft2-1.0.so without the .0 suffix; pre-link.
for base in libpangoft2-1.0 libpango-1.0; do
  if [ ! -e "$CS2_DIR/game/bin/linuxsteamrt64/${base}.so" ] \
     && [ -e "$CS2_DIR/game/bin/linuxsteamrt64/${base}.so.0" ]; then
    ln -sf "${base}.so.0" "$CS2_DIR/game/bin/linuxsteamrt64/${base}.so" || true
  fi
done

# ---------------------------------------------------------------------------
say "4. -applaunch 730 (Steam will update CS2 if needed)"
do_applaunch() {
  nohup "$STEAM_HOME/ubuntu12_32/steam" -applaunch 730 \
    -fullscreen -width 1920 -height 1080 -novid -nojoy -console \
    +exec live_autoexec \
    >>"$LOG_DIR/cs2_launch.log" 2>&1 &
  log "  applaunch sent (launcher pid=$!)"
}
do_applaunch
RELAUNCH_DONE=0

# Wait for cs2 process. Two side-effects on each iteration:
#  - poke the Steam window with Return: dismisses the focused button on
#    any modal CEF dialog (cloud-out-of-date, "Launching ... shaders", etc).
#  - every 15s, dump the open X windows + cs2/launcher state so the
#    operator can see what Steam is actually showing right now.
CS2_PID=""
for i in $(seq 1 "$CS2_LAUNCH_TIMEOUT"); do
  CS2_PID=$(pgrep -f '/linuxsteamrt64/cs2' | head -1)
  [ -n "$CS2_PID" ] && break

  # Targeted shader-skip. The "Launching Counter-Strike 2" /
  # "Processing Vulkan shaders" dialog is a separate X window. "Skip"
  # is the default-focused button; we send Return AND click its
  # absolute screen position via XTest as a belt-and-suspenders. The
  # CEF Return path can miss focus, but XTest mouse clicks reach CEF
  # reliably (same trick we use for the cloud dialog).
  SHADER_WIN=$(xwininfo -display "$DISPLAY" -root -tree 2>/dev/null \
    | awk '/"Launching Counter-Strike 2"|"Processing Vulkan shaders"/{print $1; exit}')
  if [ -n "$SHADER_WIN" ]; then
    log "  shader dialog detected: $SHADER_WIN — clicking Skip"
    wmctrl -ia "$SHADER_WIN" 2>/dev/null || true
    xdotool windowactivate --sync "$SHADER_WIN" 2>/dev/null || true
    sleep 0.1
    xdotool key --clearmodifiers Return 2>/dev/null || true
    # Skip button is on the LEFT (highlighted blue), Cancel on the
    # right. Roughly 35% across and 75% down within the dialog.
    SKIP_GEOM=$(_window_geom_abs "$SHADER_WIN")
    if [ -n "$SKIP_GEOM" ]; then
      read SAX SAY SAW SAH <<<"$SKIP_GEOM"
      SCX=$(( SAX + SAW * 35 / 100 ))
      SCY=$(( SAY + SAH * 75 / 100 ))
      log "    geom=${SAW}x${SAH}+${SAX}+${SAY}, clicking at (${SCX},${SCY})"
      xdotool mousemove --sync "$SCX" "$SCY" 2>/dev/null || true
      xdotool click 1 2>/dev/null || true
    fi
  fi

  # Auto-poke for the Cloud Out of Date dialog. Bounded to first 90s
  # of the wait — covers the case where the dialog appears late
  # because Steam first has to download cloud files (we've seen
  # 30-60s into the wait on cold-boot pods). Cs2 spawn breaks the
  # loop, so this never fires once the game is up.
  if [ "$i" -ge 3 ] && [ "$i" -le 90 ] && [ $(( i % 5 )) -eq 0 ]; then
    poke_steam_dialog
  fi

  if [ $(( i % 15 )) -eq 0 ]; then
    log "  ${i}s elapsed waiting on cs2 (likely updating + dialogs):"
    log "  open X windows:"
    list_x_windows
    # What does Steam itself say? These are the lines that tell us
    # whether Steam is still downloading, has launched cs2 already,
    # is showing a dialog, or has bailed out.
    log "  recent Steam log activity (cs2 / launch / 730):"
    grep -iE 'cs2|appid 730|applaunch|launching|playstart|"730"' \
      "$STEAM_HOME/logs/console-linux.txt" 2>/dev/null \
      | tail -10 | sed 's/^/    /' || true
    log "  recent cloud_log activity for AppID 730:"
    grep -E '\[AppID 730\]' "$STEAM_HOME/logs/cloud_log.txt" 2>/dev/null \
      | tail -5 | sed 's/^/    /' || true
  fi

  # Fallback: if cs2 still hasn't spawned after 90s, re-issue applaunch
  # once. Steam sometimes finishes a depot update + cloud sync but
  # doesn't auto-launch the game from the original applaunch session.
  if [ "$i" = 90 ] && [ "$RELAUNCH_DONE" = 0 ]; then
    log "  90s without cs2 — re-issuing -applaunch (one-shot fallback)"
    do_applaunch
    RELAUNCH_DONE=1
  fi
  sleep 1
done
[ -n "$CS2_PID" ] || {
  warn "Steam never spawned cs2 in ${CS2_LAUNCH_TIMEOUT}s"
  log "--- $LOG_DIR/cs2_launch.log ---"
  tail -40 "$LOG_DIR/cs2_launch.log"
  log "--- $STEAM_LIBRARY/steam/logs/console-linux.txt ---"
  tail -20 "$STEAM_LIBRARY/steam/logs/console-linux.txt" 2>/dev/null || true
  exit 1
}
log "  cs2 pid=$CS2_PID"
ln -sf "$STEAM_LIBRARY/steam/logs/console-linux.txt" "$LOG_DIR/cs2.log" 2>/dev/null || true

# ---------------------------------------------------------------------------
say "5. wait for CS2 window"
WIN=""
for i in $(seq 1 "$CS2_WINDOW_TIMEOUT"); do
  WIN=$(xwininfo -display "$DISPLAY" -root -tree 2>/dev/null \
    | awk '/"Counter-Strike 2"/{print $1; exit}')
  [ -n "$WIN" ] && { log "  window after ${i}s: $WIN"; break; }
  if ! kill -0 "$CS2_PID" 2>/dev/null; then
    warn "cs2 EXITED early."
    dump_log "$LOG_DIR/cs2.log"
    exit 1
  fi
  if [ $(( i % 15 )) -eq 0 ]; then
    log "  still waiting (${i}s, cs2 pid=$CS2_PID alive)"
    log "  open X windows:"
    list_x_windows
    log "  recent cs2 log activity:"
    tail -10 "$LOG_DIR/cs2.log" 2>/dev/null | sed 's/^/    /' || true
  fi
  sleep 1
done
[ -n "$WIN" ] || {
  warn "no CS2 window after ${CS2_WINDOW_TIMEOUT}s. cs2.log tail:"
  tail -60 "$LOG_DIR/cs2.log" 2>/dev/null
  exit 1
}

# ---------------------------------------------------------------------------
say "6. start match capture stream"
start_capture "$MATCH_ID" "$FPS" "$VIDEO_KBPS" false

say "done"
log "watch:    https://hls.5stack.gg/${MATCH_ID}/"
log "cs2 log:  $LOG_DIR/cs2.log"
log "gst log:  $LOG_DIR/gst-${MATCH_ID}.log"
log "stop:     src/game-streamer.sh stop-live"
