import {
  AbsoluteFill,
  Audio,
  Img,
  interpolate,
  random,
  spring,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import { z } from "zod";
import { BRAND, FONT_STACK } from "./brand";

// Cinematic 5stack outro — runs at the end of every rendered clip.
// Hot-reload preview: `cd motion && npm run dev` → pick "Outro".
//
// Timeline (3s, 60fps) — every beat is sync'd to the audio bed
// generated by motion/scripts/build-audio.sh:
//
//   0.00..0.20  background settles in (scan-line pattern + radial glow)
//   0.15..0.50  two amber "blade" lines sweep in from the sides
//                and meet at the horizontal centre line (audio: swell)
//   0.50..0.70  impact flash — white radial burst expands, blades retract
//                outward (audio: sub-bass thump + click)
//   0.55..1.00  logo emerges, scales 0.55 -> 1.00 with a damped spring,
//                rim glow pulse
//   0.95..1.30  "5STACK.gg" wordmark — letters cascade in from below.
//                "5STACK" white + ".gg" amber, same size, on one line
//   1.30..1.65  amber accent bar wipes L→R underneath the wordmark and
//                runs into the .gg portion
//   1.65..2.55  hold; ambient particle drift; soft amber pulse on logo
//   2.55..3.00  global fade to black + audio tail
//
// FLASH_S is the load-bearing impact-beat constant — keep in sync
// with motion/scripts/build-audio.sh's IMPACT_S.

const FLASH_S = 0.5;
const PARTICLE_COUNT = 22;

export const outroSchema = z.object({
  width: z.number().int().positive().default(1920),
  height: z.number().int().positive().default(1080),
  fps: z.number().int().positive().default(60),
  durationS: z.number().positive().default(3),
});

export type OutroProps = z.infer<typeof outroSchema>;

export const DEFAULT_OUTRO_PROPS: OutroProps = {
  width: 1920,
  height: 1080,
  fps: 60,
  durationS: 3,
};

const easeOutCubic = (x: number) => 1 - Math.pow(1 - x, 3);

export const Outro: React.FC<OutroProps> = ({ durationS }) => {
  const frame = useCurrentFrame();
  const { fps, width, height } = useVideoConfig();
  const t = frame / fps;
  const totalFrames = Math.round(durationS * fps);

  const logoSize = Math.round(height * 0.34);
  const titleSize = Math.round(height * 0.115);
  const accentH = Math.max(3, Math.round(height * 0.005));

  const centerY = height * 0.46;
  const logoY = centerY - logoSize * 0.55;
  const titleY = centerY + logoSize * 0.55;
  // The accent line sits beneath the wordmark; positioned via the
  // wrapping flex container so it auto-centres with the text.
  const accentTop = titleY + titleSize * 1.18;

  // ── Background ──────────────────────────────────────────────────
  const bgFade = interpolate(t, [0, 0.2], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const radialPulse =
    0.5 +
    0.5 *
      Math.sin(((Math.max(0, t - 1) * Math.PI) / Math.max(0.1, durationS - 1)));

  // ── Blade lines (sweep in 0.15..0.5, retract + fade after) ─────
  const bladeSweep = interpolate(t, [0.15, FLASH_S], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: easeOutCubic,
  });
  const bladeRetract = interpolate(t, [FLASH_S, FLASH_S + 0.35], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: easeOutCubic,
  });
  const bladeOpacity = interpolate(t, [0.15, 0.35, 0.75, 1.0], [0, 1, 1, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const bladeY = centerY;
  const bladeH = Math.max(2, Math.round(height * 0.0035));
  const bladeReach = bladeSweep * 0.46 * width * (1 + bladeRetract * 0.4);
  const bladeSplitOffset = bladeRetract * width * 0.18;
  const leftBladeWidth = bladeReach;
  const leftBladeX = width / 2 - bladeReach - bladeSplitOffset;
  const rightBladeWidth = bladeReach;
  const rightBladeX = width / 2 + bladeSplitOffset;

  const flareOpacity = interpolate(
    t,
    [FLASH_S - 0.03, FLASH_S + 0.05, FLASH_S + 0.18],
    [0, 1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  // ── Flash burst at impact ──────────────────────────────────────
  const flashOpacity = interpolate(
    t,
    [FLASH_S - 0.02, FLASH_S + 0.04, FLASH_S + 0.3],
    [0, 1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );
  const flashRadius = interpolate(t, [FLASH_S, FLASH_S + 0.35], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: easeOutCubic,
  });

  // ── Logo ───────────────────────────────────────────────────────
  const logoSpring = spring({
    frame: frame - Math.round(fps * (FLASH_S + 0.05)),
    fps,
    config: { damping: 13, mass: 0.55, stiffness: 110 },
    from: 0,
    to: 1,
  });
  const logoScale = 0.55 + 0.45 * logoSpring;
  const logoOpacity = interpolate(t, [FLASH_S, FLASH_S + 0.25], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const logoPulse =
    1 + 0.012 * Math.sin(Math.max(0, (t - 1.2) * Math.PI * 1.5));
  const logoFinalScale = logoScale * logoPulse;
  const rimGlow = Math.max(0.35, flashOpacity);

  // ── Wordmark (letter cascade — "5STACK" only) ──────────────────
  // The .gg gets delivered separately by the accent line below.
  // Cascading just the white portion keeps the entry pure and sets
  // up the bullet beat: line runs left→K, hits K, drops the .gg in.
  const STACK_CHARS = ["5", "S", "T", "A", "C", "K"];
  const WORDMARK_START = 0.95;
  const LETTER_STAGGER = 0.03;
  const LETTER_DURATION = 0.22;
  const STACK_END_T = WORDMARK_START + STACK_CHARS.length * LETTER_STAGGER;

  // ── Accent line — wipes from left edge of the wordmark to its
  // right edge, but with a deliberate beat: the tip pauses for a
  // breath at the K position to drop the .gg, then continues to
  // finish out under the .gg.
  //
  //   ACCENT_START    line begins (left edge)
  //   GG_TRIGGER_T    line tip reaches end-of-K → .gg pops in
  //   ACCENT_END_T    line completes under the .gg
  const ACCENT_START = STACK_END_T + 0.05;
  const GG_TRIGGER_T = ACCENT_START + 0.28;
  const ACCENT_END_T = GG_TRIGGER_T + 0.18;
  // K-end fraction along the line — derived from glyph widths so the
  // tip lands cleanly at the boundary between "5STACK" and ".gg".
  const STACK_LINE_FRAC = 0.66;
  // Two-segment ease so the tip "arrives" at the K, holds briefly,
  // then completes through the .gg.
  const accentT = interpolate(
    t,
    [ACCENT_START, GG_TRIGGER_T, GG_TRIGGER_T + 0.04, ACCENT_END_T],
    [0, STACK_LINE_FRAC, STACK_LINE_FRAC, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  // ── .gg bullet delivery ───────────────────────────────────────
  // Springs in with scale 0→1 + opacity fade, triggered at the
  // moment the accent tip arrives at K. A brief bullet flash plus a
  // radial spark burst sells the "line just deposited the .gg" beat.
  const ggSpring = spring({
    frame: frame - Math.round(fps * GG_TRIGGER_T),
    fps,
    config: { damping: 11, mass: 0.45, stiffness: 170 },
    from: 0,
    to: 1,
  });
  const ggOpacity = interpolate(
    t,
    [GG_TRIGGER_T - 0.02, GG_TRIGGER_T + 0.1],
    [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );
  const bulletFlashOpacity = interpolate(
    t,
    [GG_TRIGGER_T - 0.02, GG_TRIGGER_T + 0.03, GG_TRIGGER_T + 0.22],
    [0, 1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  // Geometry for placing the sparks + bullet flash at the K/.gg
  // boundary. The wordmark sits in a centred container; we measure
  // the static line width and place the spark spawn at its K-mark.
  const lineFullW = titleSize * 6.4;
  const lineLeftX = (width - lineFullW) / 2;
  const ggBoundaryX = lineLeftX + lineFullW * STACK_LINE_FRAC;
  // .gg centre is slightly to the right of the boundary (so sparks
  // appear AT the K-end, .gg itself is positioned by the wordmark
  // layout — we don't need to absolute-position it).
  const sparkX = ggBoundaryX;
  const sparkY = titleY + titleSize * 0.5;

  // ── Global fade-out ────────────────────────────────────────────
  const fadeOut = interpolate(
    frame,
    [totalFrames - Math.round(fps * 0.45), totalFrames],
    [1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  // ── Particles (deterministic seeded random) ───────────────────
  const particles = Array.from({ length: PARTICLE_COUNT }, (_, i) => {
    const seed = `p-${i}`;
    const px = random(`${seed}-x`) * width;
    const baseY = random(`${seed}-y`) * height;
    const speed = 8 + random(`${seed}-s`) * 18;
    const size = 1 + random(`${seed}-z`) * 2.5;
    const phase = random(`${seed}-p`) * Math.PI * 2;
    const driftX = Math.sin(t * 0.5 + phase) * 14;
    const y = baseY - speed * Math.max(0, t - 0.5);
    const wrapY = ((y % height) + height) % height;
    const opacity =
      0.18 +
      0.4 * (0.5 + 0.5 * Math.sin(t * 1.4 + phase)) *
        interpolate(t, [0.3, 0.9, durationS - 0.5, durationS], [0, 1, 1, 0], {
          extrapolateLeft: "clamp",
          extrapolateRight: "clamp",
        });
    return { px, py: wrapY, size, opacity, driftX };
  });

  return (
    <AbsoluteFill
      style={{
        background: BRAND.surface,
        fontFamily: FONT_STACK,
        opacity: fadeOut,
        overflow: "hidden",
      }}
    >
      <Audio src={staticFile("outro-audio.wav")} />

      {/* Radial amber glow centred behind the logo — fades in with bg,
          pulses subtly through the hold. */}
      <div
        style={{
          position: "absolute",
          inset: 0,
          background: `radial-gradient(ellipse 60% 45% at 50% 46%, hsl(33, 94%, 58%, ${0.16 + radialPulse * 0.06}) 0%, transparent 70%)`,
          opacity: bgFade,
          mixBlendMode: "screen",
        }}
      />

      {/* Vertical scan-line pattern — depth, "broadcast overlay" feel. */}
      <div
        style={{
          position: "absolute",
          inset: 0,
          opacity: bgFade * 0.35,
          backgroundImage:
            "repeating-linear-gradient(90deg, rgba(255,255,255,0.025) 0 1px, transparent 1px 6px)",
          mixBlendMode: "screen",
        }}
      />

      {/* Particle drift — sparse amber motes rising slowly. */}
      {particles.map((p, i) => (
        <div
          key={i}
          style={{
            position: "absolute",
            left: p.px + p.driftX,
            top: p.py,
            width: p.size,
            height: p.size,
            borderRadius: "50%",
            background: BRAND.amber,
            opacity: p.opacity,
            boxShadow: `0 0 ${p.size * 4}px ${BRAND.amber}`,
            pointerEvents: "none",
          }}
        />
      ))}

      {/* Blade lines — left + right amber bars converging at centre.
          Soft tail at outer edge, bright tip at the leading edge so
          the eye reads them as energy lines, not static rectangles. */}
      <div
        style={{
          position: "absolute",
          top: bladeY - bladeH / 2,
          left: leftBladeX,
          width: leftBladeWidth,
          height: bladeH,
          background: `linear-gradient(90deg, transparent 0%, hsl(33, 94%, 58%, 0.35) 35%, ${BRAND.amber} 92%, #fff 100%)`,
          boxShadow: `0 0 18px ${BRAND.amber}, 0 0 4px #fff`,
          opacity: bladeOpacity,
        }}
      />
      <div
        style={{
          position: "absolute",
          top: bladeY - bladeH / 2,
          left: rightBladeX,
          width: rightBladeWidth,
          height: bladeH,
          background: `linear-gradient(90deg, #fff 0%, ${BRAND.amber} 8%, hsl(33, 94%, 58%, 0.35) 65%, transparent 100%)`,
          boxShadow: `0 0 18px ${BRAND.amber}, 0 0 4px #fff`,
          opacity: bladeOpacity,
        }}
      />

      {/* Horizontal flare at impact — bright sliver across centre. */}
      <div
        style={{
          position: "absolute",
          top: bladeY - bladeH,
          left: 0,
          width: "100%",
          height: bladeH * 2,
          background: `linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.95) 50%, transparent 100%)`,
          boxShadow: `0 0 26px rgba(255,255,255,0.6)`,
          opacity: flareOpacity,
          pointerEvents: "none",
          mixBlendMode: "screen",
        }}
      />

      {/* Flash burst — radial white expanding from centre at impact. */}
      <div
        style={{
          position: "absolute",
          inset: 0,
          opacity: flashOpacity * 0.85,
          background: `radial-gradient(circle at 50% 46%, rgba(255,255,255,${0.95 - flashRadius * 0.6}) 0%, rgba(255,255,255,${0.4 - flashRadius * 0.4}) ${flashRadius * 35}%, transparent ${flashRadius * 70}%)`,
          pointerEvents: "none",
          mixBlendMode: "screen",
        }}
      />

      {/* Logo. */}
      <div
        style={{
          position: "absolute",
          top: logoY,
          left: (width - logoSize) / 2,
          width: logoSize,
          height: logoSize,
          opacity: logoOpacity,
          transform: `scale(${logoFinalScale})`,
          transformOrigin: "center center",
          filter: `drop-shadow(0 0 ${24 * rimGlow}px hsl(33, 94%, 58%, ${0.55 * rimGlow})) drop-shadow(0 12px 28px rgba(0,0,0,0.6))`,
        }}
      >
        <Img
          src={staticFile("5stack-logo.png")}
          style={{ width: "100%", height: "100%" }}
        />
      </div>

      {/* Wordmark — "5STACK" white cascades in; ".gg" amber is
          delivered later as a bullet (spring scale + flash + sparks)
          when the accent line tip reaches the K. .gg stays in DOM
          layout the whole time (CSS transform: scale doesn't affect
          flow), so "5STACK" doesn't shift horizontally when .gg
          appears. */}
      <div
        style={{
          position: "absolute",
          top: titleY,
          left: 0,
          width: "100%",
          textAlign: "center",
          fontSize: titleSize,
          fontWeight: 900,
          letterSpacing: "0.08em",
          lineHeight: 1,
          textShadow:
            "0 6px 22px rgba(0,0,0,0.7), 0 0 28px hsl(33, 94%, 58%, 0.18)",
        }}
      >
        {STACK_CHARS.map((char, i) => {
          const start = WORDMARK_START + i * LETTER_STAGGER;
          const o = interpolate(t, [start, start + LETTER_DURATION], [0, 1], {
            extrapolateLeft: "clamp",
            extrapolateRight: "clamp",
          });
          const dy = interpolate(t, [start, start + LETTER_DURATION], [40, 0], {
            extrapolateLeft: "clamp",
            extrapolateRight: "clamp",
            easing: easeOutCubic,
          });
          return (
            <span
              key={i}
              style={{
                display: "inline-block",
                opacity: o,
                color: BRAND.textPrimary,
                transform: `translateY(${dy}px)`,
              }}
            >
              {char}
            </span>
          );
        })}
        <span
          style={{
            display: "inline-block",
            color: BRAND.amber,
            opacity: ggOpacity,
            transform: `scale(${0.3 + 0.7 * ggSpring})`,
            transformOrigin: "left center",
            textShadow: `0 0 28px hsl(33, 94%, 58%, ${0.55 + 0.45 * bulletFlashOpacity}), 0 0 12px hsl(33, 94%, 58%, ${0.4 + 0.6 * bulletFlashOpacity})`,
          }}
        >
          .gg
        </span>
      </div>

      {/* Bullet flash — bright burst at the .gg boundary the instant
          the accent tip arrives. Sells the "line just dropped the
          .gg" beat together with the radial spark burst below. */}
      {bulletFlashOpacity > 0.001 && (
        <div
          style={{
            position: "absolute",
            top: sparkY - titleSize * 0.5,
            left: sparkX - titleSize * 0.5,
            width: titleSize,
            height: titleSize,
            background: `radial-gradient(circle, rgba(255,255,255,0.9) 0%, hsl(33, 94%, 58%, 0.55) 30%, transparent 65%)`,
            opacity: bulletFlashOpacity,
            mixBlendMode: "screen",
            pointerEvents: "none",
            filter: `blur(${titleSize * 0.04}px)`,
          }}
        />
      )}

      {/* .gg spark burst — radial spray of small amber/white motes
          shooting outward from the bullet-impact point. Mostly biased
          forward/upward like a muzzle muzzle-flash spray. */}
      {(() => {
        const GG_SPARK_COUNT = 12;
        const sparkLife = Math.max(0, t - GG_TRIGGER_T);
        if (sparkLife <= 0 || sparkLife > 0.55) return null;
        return Array.from({ length: GG_SPARK_COUNT }, (_, i) => {
          // Bias the cone of dispersion toward the upper-right (the
          // direction the line was travelling when it "fired").
          const baseAngle = -Math.PI * 0.15; // ~ -27° (up + right)
          const spread = Math.PI * 1.4; // wide-ish cone
          const angle =
            baseAngle +
            (random(`ggs-${i}-a`) - 0.5) * spread +
            (i / GG_SPARK_COUNT) * 0.4;
          const speed = titleSize * (3 + random(`ggs-${i}-s`) * 4);
          const dx = Math.cos(angle) * speed * sparkLife;
          const dy = Math.sin(angle) * speed * sparkLife;
          const size = 2 + random(`ggs-${i}-z`) * 3;
          const op = interpolate(sparkLife, [0, 0.06, 0.45], [0, 1, 0], {
            extrapolateLeft: "clamp",
            extrapolateRight: "clamp",
          });
          // Trail: scale slightly with travel for a "streak" feel.
          const stretch = 1 + sparkLife * 4;
          return (
            <div
              key={`gg-spark-${i}`}
              style={{
                position: "absolute",
                left: sparkX + dx - size / 2,
                top: sparkY + dy - size / 2,
                width: size * stretch,
                height: size,
                borderRadius: "50%",
                background: "#fff",
                boxShadow: `0 0 ${size * 6}px ${BRAND.amber}, 0 0 ${size * 2}px #fff`,
                opacity: op,
                transform: `rotate(${(angle * 180) / Math.PI}deg)`,
                pointerEvents: "none",
              }}
            />
          );
        });
      })()}

      {/* Accent line beneath the wordmark — wipes left→right, runs
          the full wordmark width so the bright right end terminates
          beneath the .gg. Gradient brightens toward the right so the
          wipe visually "lands" on the .gg side. */}
      <div
        style={{
          position: "absolute",
          top: accentTop,
          left: 0,
          width: "100%",
          display: "flex",
          justifyContent: "center",
        }}
      >
        <div
          style={{
            width: `${titleSize * 6.4}px`,
            height: accentH,
            transform: `scaleX(${accentT})`,
            transformOrigin: "left center",
            background: `linear-gradient(90deg, hsl(33, 94%, 58%, 0.5) 0%, ${BRAND.amber} 55%, #fff 100%)`,
            boxShadow: `0 0 22px ${BRAND.amber}, 0 0 6px ${BRAND.amber}`,
            borderRadius: accentH / 2,
          }}
        />
      </div>

      {/* Chromatic aberration sliver at impact — 3-frame RGB split
          over the centre line. CRT/broadcast-quality micro-detail. */}
      {(() => {
        const caOpacity = interpolate(
          t,
          [FLASH_S - 0.01, FLASH_S + 0.02, FLASH_S + 0.08],
          [0, 1, 0],
          { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
        );
        if (caOpacity <= 0.001) return null;
        const split = Math.round(width * 0.012);
        const caH = Math.round(height * 0.18);
        const caY = bladeY - caH / 2;
        return (
          <>
            <div
              style={{
                position: "absolute",
                top: caY,
                left: -split,
                width: "100%",
                height: caH,
                background:
                  "linear-gradient(90deg, transparent 0%, rgba(255,40,40,0.55) 50%, transparent 100%)",
                opacity: caOpacity,
                mixBlendMode: "screen",
                pointerEvents: "none",
              }}
            />
            <div
              style={{
                position: "absolute",
                top: caY,
                left: split,
                width: "100%",
                height: caH,
                background:
                  "linear-gradient(90deg, transparent 0%, rgba(50,140,255,0.55) 50%, transparent 100%)",
                opacity: caOpacity,
                mixBlendMode: "screen",
                pointerEvents: "none",
              }}
            />
          </>
        );
      })()}

      {/* Spark burst at impact — N amber motes spawn at centre and
          shoot radially outward, fading over ~0.6s. Deterministic
          angles so a re-render is bit-identical. */}
      {(() => {
        const SPARK_COUNT = 10;
        const sparkLife = Math.max(0, t - FLASH_S);
        if (sparkLife <= 0 || sparkLife > 0.7) return null;
        return Array.from({ length: SPARK_COUNT }, (_, i) => {
          const angle =
            (i / SPARK_COUNT) * Math.PI * 2 + random(`spark-${i}-a`) * 0.4;
          const speed = (height * 0.55) * (0.6 + random(`spark-${i}-s`) * 0.7);
          const dx = Math.cos(angle) * speed * sparkLife;
          const dy = Math.sin(angle) * speed * sparkLife;
          const size = 2 + random(`spark-${i}-z`) * 3;
          const op = interpolate(sparkLife, [0, 0.1, 0.55], [0, 1, 0], {
            extrapolateLeft: "clamp",
            extrapolateRight: "clamp",
          });
          return (
            <div
              key={`spark-${i}`}
              style={{
                position: "absolute",
                left: width / 2 + dx - size / 2,
                top: bladeY + dy - size / 2,
                width: size,
                height: size,
                borderRadius: "50%",
                background: "#fff",
                boxShadow: `0 0 ${size * 5}px ${BRAND.amber}, 0 0 ${size * 2}px #fff`,
                opacity: op,
                pointerEvents: "none",
              }}
            />
          );
        });
      })()}
    </AbsoluteFill>
  );
};
